#:schema node_modules/wrangler/config-schema.json
name = "portfolio-poc"
main = "portfolio-astro/dist/_worker.js"
compatibility_date = "2024-08-16"
assets = { directory = "portfolio-astro/dist", binding = "ASSETS" }

[build]
command = "cd portfolio-astro && npm install && npm run build"