#:schema node_modules/wrangler/config-schema.json
name = "jeff-inert-io"
main = "dist/_worker.js"
compatibility_date = "2024-08-16"
assets = { directory = "dist", binding = "ASSETS" }

[env.production]
name = "jeff-inert-io"